// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhxpgtshtnizkggiguqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoeHBndHNodG5pemtnZ2lndXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjcyNTQsImV4cCI6MjA2MDU0MzI1NH0.DRdnmf5oDQg12CDczjBlfLKUjbyygwD_LI0nnJYg8f8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);